version: '3'

services:
  inventarios:
    build: inventarios
    mem_limit: 512m  # Corrected from meme_limit to mem_limit
    ports:
      - "8080:8080"
    environment:  # Corrected from enviroment to environment
      DB_URL: jdbc:mysql://inventariosdb:3306/inventario_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234  # Corrected the typo in password
    restart: always
    depends_on:
      inventariosdb:
        condition: service_healthy

  inventariosdb:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: inventario_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10